name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # every day at 00:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate GitHub contribution snake (light)
        uses: Platane/snk@v3
        with:
          github_user_name: Sudhikumaran
          outputs: |
            ./assets/github-contribution-grid-snake.svg

      - name: Generate GitHub contribution snake (dark)
        uses: Platane/snk@v3
        with:
          github_user_name: Sudhikumaran
          outputs: |
            ./assets/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update snake"
          file_pattern: assets/*.svg
